In [ ]:
# This method was not part of the final result. Tried to use this to calculate sequence breaks. Was very inconsistent.

https://stackabuse.com/levenshtein-distance-and-text-similarity-in-python/

In [1]:
import pandas as pd
import numpy as np

In [4]:
MathID={'897','901','902','903','905','906','911','913','916','917','919','921','922','912','924','925','914'}
EnglishID={'490','492','498'}

In [5]:
Courses = pd.read_csv('ClassesCoreFeb27.csv')

In [6]:
vaa_data = pd.read_csv('VAA_Data_feb22.csv')

In [7]:
Courses.shape

(158, 6)

In [8]:
Courses

,Unnamed: 0,0,1,2,3,4
0,1,[1],"['ENGL& 230 ', 'MATH 261 ']","[4, 1]",['Mechanical Engineering'],['Washington State University']
1,3,[3],"['ENGL& 230 ', 'MATH& 163 ', 'MATH& 264 ', 'MA...","[4, 1, 2, 3, 4]",['Mechanical Engineering'],['Washington State University']
2,4,[4],['MATH 260 '],[1],['Mechanical Engineering'],['Washington State University']
3,5,[5],['MATH 261 '],[4],['Mechanical Engineering'],['Washington State University']
4,6,[6],['MATH& 146 '],[1],['Nursing'],['Washington State University']
5,7,[7],['MATH& 146 '],[4],['General Major'],['Washington State University']
6,8,[8],"['MATH& 264 ', 'MATH& 163 ', 'MATH& 264 ']","[3, 1, 2]",['Chemical Engineering'],['University of Washington Seattle']
7,10,[10],['ENGL& 102 '],[2],['Pharmacy'],['Washington State University']
8,12,[12],"['MATH 261 ', 'MATH 260 ']","[1, 2]",['Mechanical Engineering'],['Washington State University']
9,13,[13],"['ENGL& 230 ', 'MATH& 163 ', 'MATH& 264 ', 'MA...","[1, 2, 3, 2, 3]",['Aeronautics Engineering'],['University of Washington Seattle']
10,14,[14],"['MATH& 163 ', 'ENGL& 230 ', 'MATH 260 ', 'MA...","[3, 4, 2, 3]",['Mechanical Engineering'],['Washington State University']
11,16,[16],"['MATH& 163 ', 'MATH& 264 ', 'MATH 261 ', 'MA...","[3, 1, 2, 3]",['Mechanical Engineering'],['Washington State University']
12,17,[17],"['ENGL& 230 ', 'MATH& 163 ', 'MATH& 264 ', 'MA...","[4, 1, 2, 3, 4]",['Mechanical Engineering'],['Washington State University']
13,18,[18],['MATH 261 '],[3],['Mechanical Engineering'],['Washington State University']
14,19,[19],"['MATH& 163 ', 'ENGL& 230 ', 'MATH& 264 ', 'MA...","[3, 4, 1, 2, 3]",['Mechanical Engineering'],['University of Washington Seattle']
15,20,[20],"['MATH& 163 ', 'MATH& 264 ', 'MATH 261 ', 'MA...","[3, 1, 2, 3]",['General Major'],['University of Washington Seattle']
16,21,[21],['MATH& 146 '],[1],['Computer Science'],['Washington State University']
17,23,[23],"['ENGL& 101 ', 'ENGL& 230 ', 'MATH& 163 ', 'MA...","[2, 4, 1, 2, 3, 1]",['General Major'],['University of Washington Seattle']
18,24,[24],"['ENGL& 101 ', 'MATH& 163 ', 'ENGL& 102 ', 'MA...","[2, 3, 2, 2]",['Computer Science'],['Washington State University']
19,25,[25],"['MATH& 163 ', 'MATH& 264 ', 'MATH 261 ', 'MA...","[3, 4, 1, 2]",['Electrical Engineering'],['Washington State University']
20,26,[26],"['ENGL& 102 ', 'MATH& 163 ', 'MATH& 264 ']","[2, 3, 2]",['General Major'],['University of Washington Seattle']
21,27,[27],"['ENGL& 101 ', 'ENGL& 102 ', 'MATH& 146 ']","[2, 3, 4]",['Computer Science'],['Washington State University']
22,28,[28],['ENGL& 102 '],[2],['Pharmacy'],['Washington State University']
23,29,[29],"['MATH& 163 ', 'MATH& 264 ', 'MATH 260 ', 'MA...","[3, 4, 1, 2]",['Electrical Engineering'],['Washington State University']
24,30,[30],"['MATH& 163 ', 'ENGL& 102 ', 'MATH& 146 ', 'MA...","[1, 3, 2, 3]",['Computer Science'],['Washington State University']
25,31,[31],"['MATH& 163 ', 'MATH& 264 ', 'ENGL& 102 ', 'MA...","[1, 2, 2, 4, 2]",['Mechanical Engineering'],['University of Washington Seattle']
26,32,[32],"['ENGL& 101 ', 'MATH& 163 ', 'MATH 260 ', 'EN...","[2, 1, 2, 3]",['Computer Science'],['Washington State University']
27,33,[33],"['ENGL& 101 ', 'MATH& 163 ', 'MATH& 264 ', 'MA...","[2, 2, 3, 3, 4]",['Computer Engineering'],['University of Washington Bothell']
28,34,[34],['MATH& 163 '],[4],['General Major'],['Washington State University']
29,35,[35],['ENGL& 230 '],[2],['Electrical Engineering'],['University of Washington Bothell']
...,...,...,...,...,...,...
128,403,[403],['MATH 261 '],[4],['Mechanical Engineering'],['Washington State University']
129,407,[407],['MATH& 146 '],[1],['Nursing'],['Washington State University']
130,408,[408],['MATH& 146 '],[4],['General Major'],['Washington State University']
131,412,[412],"['MATH& 264 ', 'MATH& 163 ', 'MATH& 264 ']","[3, 1, 2]",['Chemical Engineering'],['University of Washington Seattle']
132,420,[420],['ENGL& 102 '],[2],['Pharmacy'],['Washington State University']
133,428,[428],"['MATH 261 ', 'MATH 260 ']","[1, 2]",['Mechanical Engineering'],['Washington State University']
134,432,[432],"['MATH& 163 ', 'MATH& 264 ', 'MATH 261 ', 'MA...","[2, 3, 2, 3]",['Aeronautics Engineering'],['University of Washington Seattle']
135,436,[436],"['MATH& 163 ', 'ENGL& 230 ', 'MATH 260 ', 'MA...","[3, 4, 2, 3]",['Mechanical Engineering'],['Washington State University']
136,444,[444],"['MATH& 163 ', 'MATH& 264 ', 'MATH 261 ', 'MA...","[3, 1, 2, 3]",['Mechanical Engineering'],['Washington State University']
137,448,[448],"['ENGL& 230 ', 'MATH& 163 ', 'MATH& 264 ', 'MA...","[4, 1, 2, 3, 4]",['Mechanical Engineering'],['Washington State University']
138,449,[449],['MATH 261 '],[3],['Mechanical Engineering'],['Washington State University']
139,453,[453],"['MATH& 163 ', 'ENGL& 230 ', 'MATH& 264 ', 'MA...","[3, 4, 1, 2, 3]",['Mechanical Engineering'],['University of Washington Seattle']
140,457,[457],"['MATH& 163 ', 'MATH& 264 ', 'MATH 260 ']","[3, 1, 3]",['General Major'],['University of Washington Seattle']
141,461,[461],['MATH& 146 '],[1],['Computer Science'],['Washington State University']
142,463,[463],['ENGL& 101 '],[2],['General Major'],['University of Washington Seattle']
143,471,[471],"['MATH& 163 ', 'MATH& 264 ', 'MATH 261 ', 'MA...","[3, 4, 1, 2]",['Electrical Engineering'],['Washington State University']
144,483,[483],"['MATH& 163 ', 'MATH& 264 ', 'MATH 260 ', 'MA...","[3, 4, 1, 2]",['Electrical Engineering'],['Washington State University']
145,487,[487],"['MATH& 163 ', 'MATH& 146 ', 'MATH 260 ']","[1, 2, 3]",['Computer Science'],['Washington State University']
146,491,[491],"['MATH& 163 ', 'MATH& 264 ', 'ENGL& 102 ', 'MA...","[1, 2, 2, 4, 2]",['Mechanical Engineering'],['University of Washington Seattle']
147,495,[495],"['ENGL& 101 ', 'MATH& 163 ', 'MATH 260 ']","[2, 1, 2]",['Computer Science'],['Washington State University']
148,499,[499],"['ENGL& 101 ', 'MATH& 163 ', 'MATH& 264 ', 'MA...","[2, 2, 3, 3, 4, 4]",['Computer Engineering'],['University of Washington Bothell']
149,504,[504],['MATH& 146 '],[3],['Computer Science and Software Engineering'],['Washington State University']
150,508,[508],"['MATH& 163 ', 'ENGL& 102 ', 'MATH 260 ']","[2, 2, 3]",['Computer Science'],['Washington State University']
151,513,[513],"['ENGL& 230 ', 'MATH& 163 ', 'MATH 260 ', 'MA...","[2, 3, 1, 2]",['Mechanical Engineering'],['Washington State University']
152,517,[517],"['MATH& 163 ', 'MATH& 264 ', 'MATH 260 ', 'MA...","[1, 2, 3, 4]",['Mechanical Engineering'],['Washington State University']
153,521,[521],"['ENGL& 101 ', 'MATH& 163 ', 'MATH& 264 ', 'MA...","[2, 3, 4, 1, 2]",['Electrical Engineering'],['Washington State University']
154,525,[525],"['MATH& 163 ', 'MATH& 264 ', 'MATH 260 ', 'MA...","[2, 3, 1, 2]",['Mechanical Engineering'],['University of Washington Seattle']
155,526,[526],"['MATH& 163 ', 'MATH& 264 ', 'MATH 260 ', 'MA...","[3, 1, 2, 3]",['Mechanical Engineering'],['Washington State University']
156,532,[532],"['ENGL& 101 ', 'MATH& 163 ', 'MATH& 264 ', 'MA...","[2, 1, 2, 3, 1]",['Mechanical Engineering'],['Washington State University']
157,536,[536],"['ENGL& 101 ', 'MATH& 163 ', 'MATH& 264 ', 'MA...","[2, 2, 3, 4, 1]",['Mechanical Engineering'],['Washington State University']

In [9]:
# Courses = Courses.drop('StudyPlanID',1)
# Courses = Courses.drop('ParameterSetID',1)
# Courses = Courses.drop('EnrollmentTypeID',1)
# Courses = Courses.drop('JobTypeID',1)
# Courses = Courses.drop('MaxNumberOfQuarters',1)
# Courses = Courses.drop('NumberCoreCoursesPerQuarter',1)
# Courses = Courses.drop('QuarterPreferenceID',1)

In [10]:
Courses.shape

(158, 6)

In [11]:
Courses
# Courses = Courses.drop('MajorID',1)
# Courses = Courses.drop('SchoolID',1)

,Unnamed: 0,0,1,2,3,4
0,1,[1],"['ENGL& 230 ', 'MATH 261 ']","[4, 1]",['Mechanical Engineering'],['Washington State University']
1,3,[3],"['ENGL& 230 ', 'MATH& 163 ', 'MATH& 264 ', 'MA...","[4, 1, 2, 3, 4]",['Mechanical Engineering'],['Washington State University']
2,4,[4],['MATH 260 '],[1],['Mechanical Engineering'],['Washington State University']
3,5,[5],['MATH 261 '],[4],['Mechanical Engineering'],['Washington State University']
4,6,[6],['MATH& 146 '],[1],['Nursing'],['Washington State University']
5,7,[7],['MATH& 146 '],[4],['General Major'],['Washington State University']
6,8,[8],"['MATH& 264 ', 'MATH& 163 ', 'MATH& 264 ']","[3, 1, 2]",['Chemical Engineering'],['University of Washington Seattle']
7,10,[10],['ENGL& 102 '],[2],['Pharmacy'],['Washington State University']
8,12,[12],"['MATH 261 ', 'MATH 260 ']","[1, 2]",['Mechanical Engineering'],['Washington State University']
9,13,[13],"['ENGL& 230 ', 'MATH& 163 ', 'MATH& 264 ', 'MA...","[1, 2, 3, 2, 3]",['Aeronautics Engineering'],['University of Washington Seattle']
10,14,[14],"['MATH& 163 ', 'ENGL& 230 ', 'MATH 260 ', 'MA...","[3, 4, 2, 3]",['Mechanical Engineering'],['Washington State University']
11,16,[16],"['MATH& 163 ', 'MATH& 264 ', 'MATH 261 ', 'MA...","[3, 1, 2, 3]",['Mechanical Engineering'],['Washington State University']
12,17,[17],"['ENGL& 230 ', 'MATH& 163 ', 'MATH& 264 ', 'MA...","[4, 1, 2, 3, 4]",['Mechanical Engineering'],['Washington State University']
13,18,[18],['MATH 261 '],[3],['Mechanical Engineering'],['Washington State University']
14,19,[19],"['MATH& 163 ', 'ENGL& 230 ', 'MATH& 264 ', 'MA...","[3, 4, 1, 2, 3]",['Mechanical Engineering'],['University of Washington Seattle']
15,20,[20],"['MATH& 163 ', 'MATH& 264 ', 'MATH 261 ', 'MA...","[3, 1, 2, 3]",['General Major'],['University of Washington Seattle']
16,21,[21],['MATH& 146 '],[1],['Computer Science'],['Washington State University']
17,23,[23],"['ENGL& 101 ', 'ENGL& 230 ', 'MATH& 163 ', 'MA...","[2, 4, 1, 2, 3, 1]",['General Major'],['University of Washington Seattle']
18,24,[24],"['ENGL& 101 ', 'MATH& 163 ', 'ENGL& 102 ', 'MA...","[2, 3, 2, 2]",['Computer Science'],['Washington State University']
19,25,[25],"['MATH& 163 ', 'MATH& 264 ', 'MATH 261 ', 'MA...","[3, 4, 1, 2]",['Electrical Engineering'],['Washington State University']
20,26,[26],"['ENGL& 102 ', 'MATH& 163 ', 'MATH& 264 ']","[2, 3, 2]",['General Major'],['University of Washington Seattle']
21,27,[27],"['ENGL& 101 ', 'ENGL& 102 ', 'MATH& 146 ']","[2, 3, 4]",['Computer Science'],['Washington State University']
22,28,[28],['ENGL& 102 '],[2],['Pharmacy'],['Washington State University']
23,29,[29],"['MATH& 163 ', 'MATH& 264 ', 'MATH 260 ', 'MA...","[3, 4, 1, 2]",['Electrical Engineering'],['Washington State University']
24,30,[30],"['MATH& 163 ', 'ENGL& 102 ', 'MATH& 146 ', 'MA...","[1, 3, 2, 3]",['Computer Science'],['Washington State University']
25,31,[31],"['MATH& 163 ', 'MATH& 264 ', 'ENGL& 102 ', 'MA...","[1, 2, 2, 4, 2]",['Mechanical Engineering'],['University of Washington Seattle']
26,32,[32],"['ENGL& 101 ', 'MATH& 163 ', 'MATH 260 ', 'EN...","[2, 1, 2, 3]",['Computer Science'],['Washington State University']
27,33,[33],"['ENGL& 101 ', 'MATH& 163 ', 'MATH& 264 ', 'MA...","[2, 2, 3, 3, 4]",['Computer Engineering'],['University of Washington Bothell']
28,34,[34],['MATH& 163 '],[4],['General Major'],['Washington State University']
29,35,[35],['ENGL& 230 '],[2],['Electrical Engineering'],['University of Washington Bothell']
...,...,...,...,...,...,...
128,403,[403],['MATH 261 '],[4],['Mechanical Engineering'],['Washington State University']
129,407,[407],['MATH& 146 '],[1],['Nursing'],['Washington State University']
130,408,[408],['MATH& 146 '],[4],['General Major'],['Washington State University']
131,412,[412],"['MATH& 264 ', 'MATH& 163 ', 'MATH& 264 ']","[3, 1, 2]",['Chemical Engineering'],['University of Washington Seattle']
132,420,[420],['ENGL& 102 '],[2],['Pharmacy'],['Washington State University']
133,428,[428],"['MATH 261 ', 'MATH 260 ']","[1, 2]",['Mechanical Engineering'],['Washington State University']
134,432,[432],"['MATH& 163 ', 'MATH& 264 ', 'MATH 261 ', 'MA...","[2, 3, 2, 3]",['Aeronautics Engineering'],['University of Washington Seattle']
135,436,[436],"['MATH& 163 ', 'ENGL& 230 ', 'MATH 260 ', 'MA...","[3, 4, 2, 3]",['Mechanical Engineering'],['Washington State University']
136,444,[444],"['MATH& 163 ', 'MATH& 264 ', 'MATH 261 ', 'MA...","[3, 1, 2, 3]",['Mechanical Engineering'],['Washington State University']
137,448,[448],"['ENGL& 230 ', 'MATH& 163 ', 'MATH& 264 ', 'MA...","[4, 1, 2, 3, 4]",['Mechanical Engineering'],['Washington State University']
138,449,[449],['MATH 261 '],[3],['Mechanical Engineering'],['Washington State University']
139,453,[453],"['MATH& 163 ', 'ENGL& 230 ', 'MATH& 264 ', 'MA...","[3, 4, 1, 2, 3]",['Mechanical Engineering'],['University of Washington Seattle']
140,457,[457],"['MATH& 163 ', 'MATH& 264 ', 'MATH 260 ']","[3, 1, 3]",['General Major'],['University of Washington Seattle']
141,461,[461],['MATH& 146 '],[1],['Computer Science'],['Washington State University']
142,463,[463],['ENGL& 101 '],[2],['General Major'],['University of Washington Seattle']
143,471,[471],"['MATH& 163 ', 'MATH& 264 ', 'MATH 261 ', 'MA...","[3, 4, 1, 2]",['Electrical Engineering'],['Washington State University']
144,483,[483],"['MATH& 163 ', 'MATH& 264 ', 'MATH 260 ', 'MA...","[3, 4, 1, 2]",['Electrical Engineering'],['Washington State University']
145,487,[487],"['MATH& 163 ', 'MATH& 146 ', 'MATH 260 ']","[1, 2, 3]",['Computer Science'],['Washington State University']
146,491,[491],"['MATH& 163 ', 'MATH& 264 ', 'ENGL& 102 ', 'MA...","[1, 2, 2, 4, 2]",['Mechanical Engineering'],['University of Washington Seattle']
147,495,[495],"['ENGL& 101 ', 'MATH& 163 ', 'MATH 260 ']","[2, 1, 2]",['Computer Science'],['Washington State University']
148,499,[499],"['ENGL& 101 ', 'MATH& 163 ', 'MATH& 264 ', 'MA...","[2, 2, 3, 3, 4, 4]",['Computer Engineering'],['University of Washington Bothell']
149,504,[504],['MATH& 146 '],[3],['Computer Science and Software Engineering'],['Washington State University']
150,508,[508],"['MATH& 163 ', 'ENGL& 102 ', 'MATH 260 ']","[2, 2, 3]",['Computer Science'],['Washington State University']
151,513,[513],"['ENGL& 230 ', 'MATH& 163 ', 'MATH 260 ', 'MA...","[2, 3, 1, 2]",['Mechanical Engineering'],['Washington State University']
152,517,[517],"['MATH& 163 ', 'MATH& 264 ', 'MATH 260 ', 'MA...","[1, 2, 3, 4]",['Mechanical Engineering'],['Washington State University']
153,521,[521],"['ENGL& 101 ', 'MATH& 163 ', 'MATH& 264 ', 'MA...","[2, 3, 4, 1, 2]",['Electrical Engineering'],['Washington State University']
154,525,[525],"['MATH& 163 ', 'MATH& 264 ', 'MATH 260 ', 'MA...","[2, 3, 1, 2]",['Mechanical Engineering'],['University of Washington Seattle']
155,526,[526],"['MATH& 163 ', 'MATH& 264 ', 'MATH 260 ', 'MA...","[3, 1, 2, 3]",['Mechanical Engineering'],['Washington State University']
156,532,[532],"['ENGL& 101 ', 'MATH& 163 ', 'MATH& 264 ', 'MA...","[2, 1, 2, 3, 1]",['Mechanical Engineering'],['Washington State University']
157,536,[536],"['ENGL& 101 ', 'MATH& 163 ', 'MATH& 264 ', 'MA...","[2, 2, 3, 4, 1]",['Mechanical Engineering'],['Washington State University']

Depending on the college and major, the sequence of maths classes to be  taken can be formed as a list. This is the ideal sequence that has to be followed. What if we use this string to compare the string of classes we have? The similarity between these values can be used as sequence break. The similarity between the strings should take in to consideration the order. The order should not change -- methods which consider the order while comparing the similarity are important. NLP is involved but not ML.

In [12]:
s1 = ['897','901','902','903','905','906','911','913','916','917','919','921','922','912','924','926','925','914']
s2 = ['924', '926', '914', '913']
s3 = ['897','901','902','903','905','906','911','913','916','917','919','921','922','912','924','925','914']
s4 = ['905','897','903','906','911','901','902']
s5 =['905','906','911','913','916','917']

In [13]:
type(s1[1])

str

In [14]:
import numpy as np

def levenshtein(seq1, seq2):  
    size_x = len(seq1) + 1
    size_y = len(seq2) + 1
    matrix = np.zeros ((size_x, size_y))
    for x in range(size_x):
        matrix [x, 0] = x
    for y in range(size_y):
        matrix [0, y] = y

    for x in range(1, size_x):
        for y in range(1, size_y):
            if seq1[x-1] == seq2[y-1]:
                matrix [x,y] = min(
                    matrix[x-1, y] + 1,
                    matrix[x-1, y-1],
                    matrix[x, y-1] + 1
                )
            else:
                matrix [x,y] = min(
                    matrix[x-1,y] + 1,
                    matrix[x-1,y-1] + 1,
                    matrix[x,y-1] + 1
                )
#     print (matrix)
    return (matrix[size_x - 1, size_y - 1])

In [86]:
print(levenshtein(s1,s2))

16.0

In [43]:
print(levenshtein(s1,s3))

1.0

In [44]:
print(levenshtein(s1,s4))

15.0

In [45]:
print(levenshtein(s1,s5))

12.0

In [16]:
from fuzzywuzzy import fuzz

In [ ]:
# The closeness of a match is often measured in terms of edit distance, 
# which is the number of primitive operations necessary to convert the string into an exact match.

In [52]:
fuzz.ratio(s1, s2)

32

In [53]:
fuzz.ratio(s1, s5)

50

In [54]:
# Not good as the order is not being considered
fuzz.ratio(s1, s4)

50

In [ ]:
# higher the value, better the plan - fuzz
# higher the value, less better the plan - levenshtein

In [66]:

print(fuzz.ratio('CSS420 CSS434','CSS434 CSS420'))
print(levenshtein('CSS420 CSS434','CSS434 CSS420'))

69
4.0

In [67]:
# incomplete and not in order plan
print(fuzz.ratio('CSS420 CSS434 CSS560','CSS434 CSS420') )
print(levenshtein('CSS420 CSS434 CSS560','CSS434 CSS420'))

67
9.0

In [68]:
# incomplete but in order
print(fuzz.ratio('CSS420 CSS434 CSS560','CSS420 CSS434') )
print(levenshtein('CSS420 CSS434 CSS560','CSS420 CSS434'))

79
7.0

In [69]:
# break in order
print(fuzz.ratio('CSS420 CSS434 CSS560','CSS420       CSS434') )
print(levenshtein('CSS420 CSS434 CSS560','CSS420       CSS434'))

67
9.0

In [70]:
# break without order
print(fuzz.ratio('CSS420 CSS434 CSS560','CSS434       CSS420') )
print(levenshtein('CSS420 CSS434 CSS560','CSS434       CSS420'))

56
10.0

In [78]:
# break later in the course sequence
print(fuzz.ratio('CSS420 CSS434 CSS560','CSS420 CSS434        ') )
print(levenshtein('CSS420 CSS434 CSS560','CSS420 CSS434          '))

68
9.0

In [20]:
# break later in the course sequence -COMPLETED
print(fuzz.ratio('CSS420 CSS434 CSS560','CSS420 CSS434 breaks CSS560') )
print(levenshtein('CSS420 CSS434 CSS560','CSS420 CSS434          CSS560'))

85
9.0

In [26]:
# completed but break in the early sequence
l1 = ['CSS420', 'CSS434', 'CSS560']
l2 = ['CSS420', 'breaks', 'CSS434']
print(fuzz.ratio(l1,l2))
print(fuzz.ratio('CSS420 CSS434 CSS560','CSS420 CSS560 CSS434') )
print(levenshtein('CSS420 CSS434 CSS560','CSS420           CSS434 CSS560'))

70
70
10.0

Levenshtein is not marking the differences in spaces. it is very dependant on